[package]
name = "fetter-mcp"
version = "0.1.0"
edition = "2024"


[dependencies]
rmcp = { version = "0.14.0", features = ["server", "macros", "transport-streamable-http-server"] }
axum = "0.8.8"
fetter = "3.2.0"
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
schemars = "1.2.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
anyhow = "1.0.100"


